---
- name: Disabling windows defender sending samples
  ansible.windows.win_powershell:
    script: |
      Set-MpPreference -MAPSReporting 0
      Set-MpPreference -SubmitSamplesConsent 2

- name: Disabling windows defender
  ansible.windows.win_powershell:
    script: |
      Set-MpPreference -DisableScanningMappedNetworkDrivesForFullScan $true
      Set-MpPreference -DisableRealtimeMonitoring $true
  when: windows_defender_status == "off"
