---
- name: Creating new Windows domain in a new forest
  win_domain:
    domain_netbios_name: "{{netbios_name}}"
    dns_domain_name: "{{domain}}"
    safe_mode_password: "{{domain_password}}"
  register: domain_install

- name: Rebooting hosts to complete domain creation
  win_reboot:
  when: domain_install.reboot_required

- name: Pause for 5 minutes for Active Directory services 
  ansible.builtin.pause:
    minutes: 5
  when: domain_install.changed

- name: Adding Administrator user to Domain Admin
  win_domain_group_membership:
    name: Domain Admins
    members:
      - Administrator

- name: Adding Administrator user to Enterprise Admin
  win_domain_group_membership:
    name: Enterprise Admins
    members:
      - Administrator
    state: present

- name: Installing xDnsServer PowerShell module
  win_psmodule:
    name: xDnsServer
    state: present

- name: Configuring DNS Forwarders
  win_dsc:
    resource_name: xDnsServerForwarder
    IsSingleInstance: "yes"
    UseRootHint: false
    IPAddresses:
      - "1.1.1.1"
      - "8.8.8.8"

- name: "Installing XactiveDirectory PowerShell module"
  win_psmodule:
    name: ActiveDirectoryDSC
    state: present