---
- name: Installing chocolatey
  ansible.windows.win_powershell:
    script: | 
      Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

- name: Installing multiple packages sequentially
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
    - git
    - 7zip
    - firefox
    - notepadplusplus
    - sysinternals
    - processhacker
    - wireshark
    - pstools

- name: Creating ansible folder
  win_file: 
    path: c:\ansible\
    state: directory

- name: Creating bginfo folder
  win_file: 
    path: c:\ansible\bginfo
    state: directory

- name: Copying bginfo config file to host
  win_copy:
    src: ./files/
    dest: c:\ansible\bginfo
  register: bginfo_config

- name: Installing bginfo 
  ansible.windows.win_powershell:
    script: |
      $vbsScript = @'
      WScript.Sleep 15000
      Dim objShell
      Set objShell = WScript.CreateObject( "WScript.Shell" )
      objShell.Run("""C:\ProgramData\chocolatey\bin\Bginfo64.exe"" /accepteula ""C:\ansible\bginfo\bginfoconf.bgi"" /silent /timer:0")
      '@

      $vbsScript | Out-File 'C:\ansible\bginfo\bginfo.vbs'
      Set-ItemProperty HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run -Name bginfo -Value 'wscript "C:\ansible\bginfo\bginfo.vbs"'
