---
- name: Ensuring ansible folder exist
  win_file: 
    path: c:\ansible\
    state: directory

- name: Uploading GPO files
  win_copy:
    src: ./files/
    dest: c:\ansible\
  register: gpo_backup

- name: Importing GPOs
  ansible.windows.win_powershell:
    script: |
      Import-GPO -BackupGpoName "Enhanced Auditing Policy" -TargetName "Enhanced Auditing Policy" -Path 'c:\ansible\GPOs\' -CreateIfNeeded
      Import-GPO -BackupGpoName "PowerShell Logging" -TargetName "PowerShell Logging" -Path 'c:\ansible\GPOs\' -CreateIfNeeded
      New-GPLink -Name 'Enhanced Auditing Policy' -Target {{target}} -Enforced yes
      New-GPLink -Name 'Enhanced Auditing Policy' -Target {{target}} -Enforced yes
      