---
- name: Ensuring ansible folder exist
  win_file: 
    path: c:\ansible\
    state: directory

- name: Uploading GPO files
  win_copy:
    src: ./files/
    dest: c:\ansible\
  register: gpo_backup

- name: Importing GPOs
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
        [String]
        $target_ou
      )

      if (Get-GPO -All | Where-Object {$_.DisplayName -contains "Enhanced Auditing Policy"}) {
        $Ansible.Changed = $false
      } else {
        Import-GPO -BackupGpoName "Enhanced Auditing Policy" -TargetName "Enhanced Auditing Policy" -Path 'c:\ansible\GPO\' -CreateIfNeeded
        $Ansible.Changed = $true
      }

      if (Get-GPO -All | Where-Object {$_.DisplayName -contains "PowerShell Logging"}) {
        $Ansible.Changed = $false
      } else {
        Import-GPO -BackupGpoName "PowerShell Logging" -TargetName "PowerShell Logging" -Path 'c:\ansible\GPO\' -CreateIfNeeded
        $Ansible.Changed = $true
      }

      New-GPLink -Name 'Enhanced Auditing Policy' -Target $target_ou -Enforced yes
      New-GPLink -Name 'PowerShell Logging' -Target $target_ou -Enforced yes
      gpupdate /force
    parameters:
      target_ou: "{{target_ou}}"