---
- name: Installing IIS
  win_feature:
    name: "Web-Server"
    state: present
    restart: yes
    include_sub_features: yes
    include_management_tools: yes

- name: Changing IIS server port
  ansible.windows.win_powershell:
    script: |
      Set-WebBinding -Name "Default Web Site" -BindingInformation "*:80:" -PropertyName "Port" -Value "8080"

- name: Copying web files to server
  win_copy:
    src: "files/"
    dest: "C:\\inetpub\\wwwroot\\"

- name: Creating uploads file
  win_file: 
    path: c:\inetpub\wwwroot\uploads
    state: directory

- name: Editing uploads file Acls
  ansible.windows.win_powershell:
    script: |
      $NewAcl = Get-Acl -Path "c:\inetpub\wwwroot\uploads"
      # Set properties
      $identity = "IIS_IUSRS"
      $fileSystemRights = "FullControl"
      $type = "Allow"
      # Create new rule
      $fileSystemAccessRuleArgumentList = $identity, $fileSystemRights, $type
      $fileSystemAccessRule = New-Object -TypeName System.Security.AccessControl.FileSystemAccessRule -ArgumentList $fileSystemAccessRuleArgumentList
      # Apply new rule
      $NewAcl.SetAccessRule($fileSystemAccessRule)
      Set-Acl -Path "c:\inetpub\wwwroot\uploads" -AclObject $NewAcl

- name: Installing xNetworking Powershell module
  win_psmodule:
    name: xNetworking
    state: present

- name: Opening 443 on firewall
  win_dsc:
    resource_name: xFirewall
    Name: "Access to web services (TCP-In)"
    Ensure: present
    Enabled: True
    Profile: "Domain"
    Direction: "Inbound"
    Localport: "443"
    Protocol: "TCP"
    Description: "Open port 443"

- name: Opening 8080 on firewall
  win_dsc:
    resource_name: xFirewall
    Name: "Access to web services (TCP-In)"
    Ensure: present
    Enabled: True
    Profile: "Domain"
    Direction: "Inbound"
    Localport: "8080"
    Protocol: "TCP"
    Description: "Open port 8080"
