---
# -----------------------------------------
# load config data
- import_playbook: data.yml
  vars:
    data_path: "./config/data/"

# -----------------------------------------
# Configure basic windows settings
- name: Configuring basic settings (hostname, local admin password ex.)
  hosts: windows
  roles:
    - {role: 'settings/hostname', tags: 'hostname'}
    - {role: 'settings/admin_password', tags: 'admin_password'}
    - {role: 'settings/local_admin', tags: 'local_admin'}
  vars:
    hostname: "{{lab.hosts[dict_key].hostname}}"
    local_admin_password: "{{lab.hosts[dict_key].local_admin_password}}"

# -----------------------------------------
# Configure primary domain controllers
- name: Configuring primary DCs
  hosts: primary_domain_controllers
  roles:
    - {role: 'ad/domain_controller/primary', tags: 'dc_primary'}
  vars:
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_password: "{{lab.domains[domain].domain_password}}"
    netbios_name: "{{lab.domains[domain].netbios_name}}"

# -----------------------------------------
# Configure child domain controllers
- name: Configuring child DCs
  hosts: child_domain_controllers
  roles:
    - {role: 'ad/domain_controller/child', tags: 'dc_child'}
  vars:
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_password: "{{lab.domains[domain].domain_password}}"
    netbios_name: "{{lab.domains[domain].netbios_name}}"
    parent_domain: "{{'.'.join(domain.split('.')[1:])}}"
    parent_domain_password: "{{lab.domains[parent_domain].domain_password}}"
    source_dc: "{{lab.hosts[lab.domains[parent_domain].dc].hostname}}.{{parent_domain}}"

# -----------------------------------------
# Import GPO policies
- name: Importing GPO policies
  hosts: domain_controllers
  roles:
    - {role: 'ad/configurations/gpos', tags: 'ad_gpos'}
  vars:
    domain: "{{lab.hosts[dict_key].domain}}"
    target_ou: "{{lab.domains[domain].path}}"

# -----------------------------------------
# Configure domain servers
- name: Adding server to domain
  hosts: servers
  roles:
    - { role: 'ad/domain_machines', tags: 'domain_servers', type: 'server'}
  vars:
    member_domain: "{{lab.hosts[dict_key].domain}}"
    domain_password: "{{lab.domains[member_domain].domain_password}}"

# -----------------------------------------
# Configure domain desktops
- name: Adding desktops to domain
  hosts: desktops
  roles:
    - { role: 'ad/domain_machines', tags: 'domain_desktops', type: 'desktop'}
  vars:
    member_domain: "{{lab.hosts[dict_key].domain}}"
    domain_password: "{{lab.domains[member_domain].domain_password}}"

