---
# -----------------------------------------
# WIN02 files containing sensitive information
- name: Vulnerability scheduled tasks adm_dooku
  hosts: win02
  roles: 
    - {role: 'vulnerabilities/adm_cdooku_scheduled_task', tags: 'adm_cdooku_scheduled_task'}
  vars:
    runas_user: "security\\c.dooku"
    runas_password: "TwiceThePride07*"