---
# -----------------------------------------
# WIN02 files containing sensitive information
- name: Vulnerability scheduled tasks adm_dooku
  hosts: win02
  roles: 
    - {role: 'vulnerabilities/adm_cdooku_scheduled_task', tags: 'adm_cdooku_scheduled_task'}
  vars:
    runas_user: "security\\c.dooku"
    runas_password: "TwiceThePride07*"

# -----------------------------------------
# SRV02 autologon
- name: Autologon as a.skywalker on SRV02
  hosts: srv02
  roles:
    - {role: 'vulnerabilities/auto_logon_askywalker', tags: 'auto_logon_askywalker'}
  vars:
    auto_logon_username: "a.skywalker"
    auto_logon_password: "TheGreatestJediEv3r!"
