---
- name: Preforming interactive logon as a.skywalker
  ansible.windows.win_powershell:
    script: |
      $Action = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument 'echo @"
Set x=CreateObject("wscript.shell")
wscript.sleep 1500
x.sendkeys "TheGreatestJediEv3r!"
x.sendkeys "{enter}"
"@ > $env:temp\\runas_pass.vbs
start $env:temp\\runas_pass.vbs
runas /user:security\\a.skywalker "calc.exe"
Start-Sleep -Seconds 10
Stop-Process -Name "win32calc" -Force'
      $Trigger = New-ScheduledTaskTrigger -Once -At (Get-Date) -RepetitionInterval (New-TimeSpan -Minutes 5) -RepetitionDuration ([System.TimeSpan]::MaxValue)
      $Settings = New-ScheduledTaskSettingsSet
      $Task = New-ScheduledTask -Action $Action -Trigger $Trigger -Settings $Settings
      Register-ScheduledTask -TaskName 'Skywalker' -InputObject $Task'