---
- name: "Configuring DNS settings to {{dns_domain}}"
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
      - "{{dns_domain}}"
    log_path: C:\dns_log.txt

- name: Adding desktops to domain"
  win_domain_membership:
    dns_domain_name: "{{member_domain}}"
    domain_admin_user: "{{member_domain}}\\Administrator"
    domain_admin_password: "{{domain_password}}"
    state: domain
  register: domain_state

- name: Reboot if needed
  win_reboot:
  when: domain_state.reboot_required